### ISSUE TITLE
Удаление уровня инициализации Injected

### ISSUE THREAD

**Issue by zcxv** [zcxv/finex-server#7]
**Описание**: необходимо удалить не нужный уровень инициализации. Как замена - использование private module / private binding, либо получение провайдеров напрямую в модуле, через биндер.

**Требуется сделать**:
1. Удалить аннотацию `InjectedModule`
2. Удалить интерфейс `ServerContext`
3. Перевести использование инжектора из ServerContext на GlobalContext
4. В ServerApplication необходимо удалить создание server-context инжектора и работу с ServerContext

**Comment by Empericall** [comment]
@zcxv выполнено. Посмотри, пожалуйста.
Branch: #7_injected_init_removal
